### ISSUE TITLE
No icon on Grasshopper

### ISSUE THREAD

**Issue by netsonicyxf** [SOFiSTiK/gh_sofistik#10]
Rhino 6 SR21, GH 1.0.0007
https://s2.ax1x.com/2020/01/20/1izFET.png

**Comment by jurekure** [comment]
yes the same thing with Rhino6 SR17 and latest gh_sofistik... old version gh_sofistik is working with no problem!

**Comment by HannaIsabella** [comment]
> Hi,
> the only way i could reproduce this behaviour was by enabling
> "Memory load *.GHA assemblies using COFF byte arrays" in the Grasshopper Developer Settings.
> Maybe you could try do disable this option and try again.
> You can find it by typing "GrasshopperDeveloperSettings" in the Rhino Command Line.
> 
> ![AssemblyLoadingCOFF](https://user-images.githubusercontent.com/50671971/72791782-35ff9980-3c38-11ea-90a3-4c81e11e10fc.PNG)

I have had the same issue and can verify that this solution fixes the problem.

**Comment by emanuelknapp** [comment]
Hi,
so this issue should be solved since the latest commit contains a assembly instruction which forces the assembly to load without using COFF byte arrays.

**Comment by netsonicyxf** [comment]
My default setting is unchecked (disabled?), but the icons are still missing.
https://s2.ax1x.com/2020/01/24/1ZgMCV.png

**Comment by emanuelknapp** [comment]
ok,
the only ways i know atm to reproduce this behavior is by renaming the gh_sofistik.gha or by enabling "reading with Coff byte arrays" (which should be soved now).
Have you renamed your assembly?
Or maybe you can check the grasshopper preferences. file -> Preferences.. -> Solver
This shows a list of loaded plugins along with their Load Mechanism.
The gh_sofistik configuration should be 
"This plugin is allowed to choose what loading method is most appropriate"

**Comment by netsonicyxf** [comment]
renaming the gh_sofistik.gha works for me.
Thanks Emanuel Knapp

**Comment by emanuelknapp** [comment]
You are welcome, i'm glad that fixed the problem.
